### ISSUE TITLE
setup_configuration opennotificaties NRC config not working

### ISSUE THREAD

**Issue by sjoerdie** [maykinmedia/django-setup-configuration#16]
When running setup_configuration with the variables described in https://github.com/open-zaak/open-notificaties/blob/main/docker-compose.yml the configuration is not fully completed:

![image](https://github.com/user-attachments/assets/1079f6ce-f96e-45bc-b5db-0a5210103717)

Here is an example of an instance manually configured by a human:
![image](https://github.com/user-attachments/assets/9713a8c3-be65-47be-881a-f6bc5995e6ad)

Everything is properly configured on the openzaak side.

Please make sure everything can be configured with setup_configuration as described here: https://open-zaak.readthedocs.io/en/latest/installation/config/openzaak_config.html

These are the envvars that are set when running `./src/manage.py setup_configuration` 

```
SITES_CONFIG_ENABLE=True
OPENZAAK_DOMAIN=opennotificaties.test.deducted.opengem.nl
OPENNOTIFICATIES_DOMAIN=opennotificaties.test.deducted.opengem.nl
OPENZAAK_ORGANIZATION=Gemeente deducted
OPENNOTIFICATIES_ORGANIZATION=Gemeente deducted
NOTIF_OPENZAAK_CONFIG_ENABLE=True
NOTIF_OPENZAAK_CLIENT_ID=opennotficaties
NOTIF_OPENZAAK_SECRET=deducted

OPENZAAK_NOTIF_CONFIG_ENABLE=True
NOTIF_API_ROOT=https://opennotificaties.test.deducted.opengem.nl/api/v1/
OPENZAAK_NOTIF_CLIENT_ID=openzaak
OPENZAAK_NOTIF_SECRET=deducted
AUTHORIZATION_CONFIG_ENABLE=True
AUTORISATIES_API_ROOT=https://openzaak.test.deducted.opengem.nl/autorisaties/api/v1/
```
In the admin in looks like this:

![image](https://github.com/user-attachments/assets/75661291-325a-489b-ac38-136946bd5ba0)

![image](https://github.com/user-attachments/assets/ccc89dde-f90e-4884-a0e2-c592d9c92dc7)

![image](https://github.com/user-attachments/assets/6599826c-edf0-4896-8588-54514a379622)

For the manually configured instance it looks like this:
![image](https://github.com/user-attachments/assets/38c635e0-c5eb-44f8-8019-fc4ac60eac30)

![image](https://github.com/user-attachments/assets/8525de8b-75ff-48ab-a3d5-1928b3f113f6)

![image](https://github.com/user-attachments/assets/1c10dff7-d943-46e5-8021-89fb286889a0)

Thank you.

**Comment by alextreme** [comment]
Discussed and moved to TODO as the missing NRC step is clear to me

**Comment by joeribekker** [comment]
Superseeded by open-zaak/open-notificaties#200
